// Shape of the content modules generated by scripts/legal_docx_to_ts.py.
export type Inline = string | { b: string } | { br: true }

export type LegalBlock =
  | { type: 'heading'; text: string }
  | { type: 'subheading'; text: string }
  | { type: 'paragraph'; content: Inline[] }
  | { type: 'list'; items: { content: Inline[]; children?: Inline[][] }[] }

export type LegalDocument = {
  effectiveDate: string | null
  blocks: LegalBlock[]
}
