# Generated by Django 5.1.15 on 2026-09-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batch", "0001_initial"),
        ("core", "0008_payment_numbering_sequences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsession",
            name="training_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.trainingtype",
            ),
        ),
    ]
