# Generated by Django 5.1.15 on 2026-09-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_batch_residential_monthly_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='residential_monthly_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
