# Generated by Django 5.1.15 on 2026-09-29 00:00

import decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_alter_batch_residential_monthly_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='monthly_fee',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))],
            ),
        ),
        migrations.AlterField(
            model_name='batch',
            name='residential_monthly_fee',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))],
            ),
        ),
    ]
