# Generated by Django 5.1.15 on 2026-08-26 12:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_agecategory_assessmentcriterion_documenttype_and_more"),
        ("people", "0002_guardian_staff_studentguardian"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enquiry_no", models.CharField(max_length=20, unique=True)),
                ("student_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=1
                    ),
                ),
                ("guardian_name", models.CharField(max_length=200)),
                ("guardian_mobile", models.CharField(max_length=15)),
                ("guardian_email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("school", models.CharField(blank=True, max_length=200)),
                ("class_grade", models.CharField(blank=True, max_length=20)),
                ("cricket_experience", models.TextField(blank=True)),
                (
                    "playing_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("batsman", "Batsman"),
                            ("bowler", "Bowler"),
                            ("all_rounder", "All-rounder"),
                            ("wicketkeeper", "Wicketkeeper"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "batting_style",
                    models.CharField(
                        blank=True,
                        choices=[("right_handed", "Right-handed"), ("left_handed", "Left-handed")],
                        max_length=20,
                    ),
                ),
                (
                    "bowling_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("right_arm_fast", "Right-arm fast"),
                            ("right_arm_medium", "Right-arm medium"),
                            ("right_arm_offbreak", "Right-arm offbreak"),
                            ("right_arm_legbreak", "Right-arm legbreak (leg spin)"),
                            ("left_arm_fast", "Left-arm fast"),
                            ("left_arm_medium", "Left-arm medium"),
                            ("left_arm_orthodox", "Left-arm orthodox spin"),
                            ("left_arm_chinaman", "Left-arm chinaman (wrist spin)"),
                            ("none", "Does not bowl"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_club", models.CharField(blank=True, max_length=200)),
                ("residential_required", models.BooleanField(default=False)),
                ("referred_by", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("trial_scheduled", "Trial scheduled"),
                            ("converted", "Converted"),
                            ("not_interested", "Not interested"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_enquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="people.person",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enquiries",
                        to="core.enquirysource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnquiryFollowUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contacted_on", models.DateTimeField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("visit", "Visit"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("next_action_on", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="enquiry.enquiry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
