# Generated by Django 5.1.15 on 2026-09-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('trial_scheduled', 'Trial scheduled'), ('converted', 'Converted'), ('not_interested', 'Not interested'), ('lost', 'Lost')], db_index=True, default='new', max_length=20),
        ),
    ]
