# Generated by Django 5.1.15 on 2026-09-11 13:29

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0009_consentrecord'),
        ('core', '0006_rcp_numbering_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFeeLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_lines', to='admission.admission')),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.feehead')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('admission', 'fee_head'), name='unique_admission_fee_head')],
            },
        ),
    ]
