# Generated by Django 5.1.15 on 2026-08-26 12:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0002_guardian_staff_studentguardian"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentPortalAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_portal_enabled", models.BooleanField(default=False)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("en", "English"), ("bn", "Bengali"), ("hi", "Hindi")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("sms_opt_in", models.BooleanField(default=True)),
                ("whatsapp_opt_in", models.BooleanField(default=True)),
                ("email_opt_in", models.BooleanField(default=True)),
                ("push_opt_in", models.BooleanField(default=False)),
                (
                    "guardian",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_settings",
                        to="people.guardian",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
