# Generated by Django 5.1.15 on 2026-09-11 11:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agecategory_assessmentcriterion_documenttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=150)),
                ('body_text', models.TextField()),
                ('version', models.CharField(max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('applies_to', models.CharField(choices=[('residential', 'Residential'), ('non_residential', 'Non-residential'), ('both', 'Both')], default='both', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='documenttype',
            name='required_stage',
            field=models.CharField(blank=True, choices=[('at_admission', 'At admission'), ('before_first_session', 'Before first session'), ('profile_completion', 'Profile completion')], max_length=20),
        ),
        migrations.AddField(
            model_name='season',
            name='age_cutoff_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
