// Generated by scripts/legal_docx_to_ts.py from
// backend/docs_files/ADAMAS CRICKET ACADEMY  CHILDREN’S PRIVACY & PARENTAL CONSENT POLICY  .docx
// Do not edit by hand — update the .docx and re-run the script.
import type { LegalDocument } from '../types'

export const childrensPrivacyContent: LegalDocument = {
  "effectiveDate": null,
  "blocks": [
    {
      "type": "paragraph",
      "content": [
        "Adamas Cricket Academy recognises the importance of protecting the privacy, safety and well-being of children and young athletes participating in its programmes."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "This Children's Privacy & Parental Consent Policy explains how information relating to students below 18 years of age is collected, used, stored and shared and the role of parents or legal guardians in providing consent for the student's participation in Academy activities."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "This Policy should be read together with the ",
        {
          "b": "Privacy Policy"
        },
        ", ",
        {
          "b": "Terms & Conditions"
        },
        ", and other applicable policies of Adamas Cricket Academy."
      ]
    },
    {
      "type": "heading",
      "text": "1. Scope"
    },
    {
      "type": "paragraph",
      "content": [
        "This Policy applies to students below 18 years of age who:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Apply for admission to Adamas Cricket Academy;"
          ]
        },
        {
          "content": [
            "Participate in cricket training or coaching;"
          ]
        },
        {
          "content": [
            "Attend Academy camps, trials or events;"
          ]
        },
        {
          "content": [
            "Participate in tournaments or competitions;"
          ]
        },
        {
          "content": [
            "Use Academy facilities or services; or"
          ]
        },
        {
          "content": [
            "Otherwise participate in Academy-related activities."
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "For the purposes of this Policy, “parent/guardian” means the student's parent or legally authorised guardian."
      ]
    },
    {
      "type": "heading",
      "text": "2. Parental / Guardian Consent"
    },
    {
      "type": "paragraph",
      "content": [
        "For students below 18 years of age, the admission application and applicable consents must be provided by a parent or legal guardian."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The parent/guardian confirms that:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "They are the parent or legally authorised guardian of the student."
          ]
        },
        {
          "content": [
            "The information provided during the admission process is accurate and complete."
          ]
        },
        {
          "content": [
            "They have authority to provide the required consent on behalf of the student."
          ]
        },
        {
          "content": [
            "They have read and understood the Academy's applicable policies."
          ]
        },
        {
          "content": [
            "They consent to the student's participation in Academy training and related activities, subject to the Academy's rules and policies."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "3. Information Collected About Children"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy may collect information reasonably necessary for admission, training, administration, safety and participation in Academy activities."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "This may include:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Student's full name"
          ]
        },
        {
          "content": [
            "Date of birth"
          ]
        },
        {
          "content": [
            "Age and age group"
          ]
        },
        {
          "content": [
            "Gender"
          ]
        },
        {
          "content": [
            "Photograph"
          ]
        },
        {
          "content": [
            "School/educational institution"
          ]
        },
        {
          "content": [
            "Residential/contact details"
          ]
        },
        {
          "content": [
            "Parent/guardian details"
          ]
        },
        {
          "content": [
            "Emergency contact information"
          ]
        },
        {
          "content": [
            "Cricket experience and achievements"
          ]
        },
        {
          "content": [
            "Trial and assessment information"
          ]
        },
        {
          "content": [
            "Attendance and training records"
          ]
        },
        {
          "content": [
            "Tournament and competition information"
          ]
        },
        {
          "content": [
            "Relevant medical, fitness or injury information provided for safety purposes"
          ]
        },
        {
          "content": [
            "Payment and admission records"
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy will seek to collect only information that is reasonably necessary for legitimate Academy-related purposes."
      ]
    },
    {
      "type": "heading",
      "text": "4. Purpose of Collecting Children's Information"
    },
    {
      "type": "paragraph",
      "content": [
        "Information relating to a child may be used for:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Processing and managing admission."
          ]
        },
        {
          "content": [
            "Creating and maintaining student records."
          ]
        },
        {
          "content": [
            "Organising training batches and schedules."
          ]
        },
        {
          "content": [
            "Recording attendance and participation."
          ]
        },
        {
          "content": [
            "Managing tournaments, competitions, trials and events."
          ]
        },
        {
          "content": [
            "Assessing sporting performance and development."
          ]
        },
        {
          "content": [
            "Maintaining emergency and safety information."
          ]
        },
        {
          "content": [
            "Communicating with parents/guardians."
          ]
        },
        {
          "content": [
            "Processing applicable fees and payments."
          ]
        },
        {
          "content": [
            "Complying with applicable legal, institutional and sporting requirements."
          ]
        },
        {
          "content": [
            "Providing and improving Academy services."
          ]
        },
        {
          "content": [
            "Maintaining appropriate records of Academy activities."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "5. Communication With Parents / Guardians"
    },
    {
      "type": "paragraph",
      "content": [
        "For students below 18 years of age, the Academy may primarily communicate with the registered parent/guardian regarding matters including:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Admission"
          ]
        },
        {
          "content": [
            "Fees and payments"
          ]
        },
        {
          "content": [
            "Training schedules"
          ]
        },
        {
          "content": [
            "Attendance"
          ]
        },
        {
          "content": [
            "Holidays"
          ]
        },
        {
          "content": [
            "Tournaments"
          ]
        },
        {
          "content": [
            "Events"
          ]
        },
        {
          "content": [
            "Performance-related matters"
          ]
        },
        {
          "content": [
            "Safety and medical concerns"
          ]
        },
        {
          "content": [
            "Important Academy announcements"
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy may communicate directly with the student where necessary for training, sporting, operational or safety-related purposes, while maintaining appropriate safeguards."
      ]
    },
    {
      "type": "heading",
      "text": "6. Photographs & Video Recordings"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy may photograph or record children during:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Training sessions"
          ]
        },
        {
          "content": [
            "Cricket matches"
          ]
        },
        {
          "content": [
            "Trials"
          ]
        },
        {
          "content": [
            "Tournaments"
          ]
        },
        {
          "content": [
            "Camps"
          ]
        },
        {
          "content": [
            "Academy events"
          ]
        },
        {
          "content": [
            "Award ceremonies"
          ]
        },
        {
          "content": [
            "Other Academy-related activities"
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "With appropriate parental/guardian consent, such photographs and recordings may be used for legitimate Academy-related purposes, including:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Academy website"
          ]
        },
        {
          "content": [
            "Social media"
          ]
        },
        {
          "content": [
            "Promotional materials"
          ]
        },
        {
          "content": [
            "Brochures and publications"
          ]
        },
        {
          "content": [
            "News and media coverage"
          ]
        },
        {
          "content": [
            "Event documentation"
          ]
        },
        {
          "content": [
            "Academy reports and presentations"
          ]
        },
        {
          "content": [
            "Highlighting student and Academy achievements"
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy will make reasonable efforts to use such content appropriately and in connection with Academy activities."
      ]
    },
    {
      "type": "heading",
      "text": "7. Medical & Safety Information"
    },
    {
      "type": "paragraph",
      "content": [
        "Parents/guardians are responsible for informing the Academy about any relevant medical condition, allergy, injury, medication requirement or physical limitation that may affect the child's participation."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Such information may be used to:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Assess participation requirements;"
          ]
        },
        {
          "content": [
            "Take reasonable safety precautions;"
          ]
        },
        {
          "content": [
            "Respond to injuries or emergencies;"
          ]
        },
        {
          "content": [
            "Inform authorised coaches or staff where necessary; and"
          ]
        },
        {
          "content": [
            "Arrange appropriate medical assistance where required."
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy will endeavour to handle such information responsibly and restrict access to authorised persons on a need-to-know basis."
      ]
    },
    {
      "type": "heading",
      "text": "8. Sharing Children's Information"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy will not ordinarily sell or commercially trade children's personal information."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Information relating to a child may be shared with authorised persons or organisations where reasonably necessary for legitimate Academy-related purposes, including:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Academy management and authorised employees"
          ]
        },
        {
          "content": [
            "Coaches and authorised support staff"
          ]
        },
        {
          "content": [
            "Adamas University and/or associated institutional entities, where applicable"
          ]
        },
        {
          "content": [
            "Sports associations and governing bodies"
          ]
        },
        {
          "content": [
            "Tournament organisers"
          ]
        },
        {
          "content": [
            "Event organisers"
          ]
        },
        {
          "content": [
            "Medical or emergency service providers"
          ]
        },
        {
          "content": [
            "Payment and financial service providers"
          ]
        },
        {
          "content": [
            "Technology and hosting service providers"
          ]
        },
        {
          "content": [
            "Government, regulatory or law-enforcement authorities where legally required"
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy will seek to limit sharing to information reasonably necessary for the relevant purpose."
      ]
    },
    {
      "type": "heading",
      "text": "9. Protection of Children's Information"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy takes reasonable administrative, technical and organisational measures to protect children's information against unauthorised access, misuse, alteration, disclosure, loss or destruction."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Access to children's personal information may be restricted to authorised personnel based on their responsibilities."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "However, no electronic system or method of data transmission can be guaranteed to be completely secure."
      ]
    },
    {
      "type": "heading",
      "text": "10. Parent / Guardian Rights"
    },
    {
      "type": "paragraph",
      "content": [
        "Subject to applicable laws, regulations and Academy policies, parents/guardians may:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Request information about the personal information held about their child;"
          ]
        },
        {
          "content": [
            "Request correction of inaccurate or outdated information;"
          ]
        },
        {
          "content": [
            "Request updating of contact or other relevant information;"
          ]
        },
        {
          "content": [
            "Raise concerns regarding the handling of their child's personal information;"
          ]
        },
        {
          "content": [
            "Request withdrawal of consent where consent is the applicable basis for processing."
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy may require reasonable verification of the identity and authority of the person making such a request."
      ]
    },
    {
      "type": "heading",
      "text": "11. Withdrawal of Parental Consent"
    },
    {
      "type": "paragraph",
      "content": [
        "A parent/guardian may request withdrawal of consent for a particular activity or use of information by contacting the Academy through its official communication channel."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Withdrawal of consent may affect the child's ability to participate in certain activities where the relevant information or consent is necessary."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "For example, withdrawal of consent for certain photographs or recordings may limit the Academy's ability to include the child in promotional or media content."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Withdrawal of consent will not affect processing that was lawfully carried out before the withdrawal."
      ]
    },
    {
      "type": "heading",
      "text": "12. Retention of Children's Information"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy may retain children's information for as long as reasonably necessary for:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Providing Academy services;"
          ]
        },
        {
          "content": [
            "Maintaining admission and student records;"
          ]
        },
        {
          "content": [
            "Maintaining financial records;"
          ]
        },
        {
          "content": [
            "Tournament and sporting records;"
          ]
        },
        {
          "content": [
            "Safety and emergency purposes;"
          ]
        },
        {
          "content": [
            "Legal, regulatory or institutional requirements;"
          ]
        },
        {
          "content": [
            "Resolving disputes or complaints; and"
          ]
        },
        {
          "content": [
            "Legitimate administrative purposes."
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "When information is no longer required, it may be deleted, anonymised or securely disposed of in accordance with applicable requirements and the Academy's record-retention practices."
      ]
    },
    {
      "type": "heading",
      "text": "13. Parent / Guardian Responsibility"
    },
    {
      "type": "paragraph",
      "content": [
        "Parents/guardians are expected to:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Provide accurate and complete information."
          ]
        },
        {
          "content": [
            "Keep contact and emergency information updated."
          ]
        },
        {
          "content": [
            "Inform the Academy of relevant medical or safety concerns."
          ]
        },
        {
          "content": [
            "Ensure that the child follows Academy rules and safety instructions."
          ]
        },
        {
          "content": [
            "Review important Academy communications."
          ]
        },
        {
          "content": [
            "Notify the Academy if there is any change in guardianship or authority relating to the child."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "14. Child Safety & Welfare"
    },
    {
      "type": "paragraph",
      "content": [
        "The safety and well-being of students is a priority of Adamas Cricket Academy."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Students are expected to behave respectfully towards coaches, staff and fellow students. Concerns relating to bullying, harassment, inappropriate behaviour, abuse, safety or any other matter affecting a child's welfare should be reported to Academy management through the appropriate grievance mechanism."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy may take appropriate action and, where necessary, involve the parent/guardian or competent authority."
      ]
    },
    {
      "type": "heading",
      "text": "15. Grievances Relating to Children"
    },
    {
      "type": "paragraph",
      "content": [
        "Parents/guardians may raise concerns relating to the collection, use, disclosure or handling of their child's information or any other Academy-related matter through the Academy's ",
        {
          "b": "Grievance Redressal Policy"
        },
        "."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        {
          "b": "Grievance Email:"
        },
        " cricketacademy@adamasunitedsports.com"
      ]
    },
    {
      "type": "heading",
      "text": "16. Changes to this Policy"
    },
    {
      "type": "paragraph",
      "content": [
        "Adamas Cricket Academy may update this Policy from time to time to reflect changes in its operations, technology, institutional requirements or applicable laws and regulations."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The latest version may be published on the Academy's admission portal or official communication channels."
      ]
    },
    {
      "type": "heading",
      "text": "PARENT / GUARDIAN CONSENT"
    },
    {
      "type": "paragraph",
      "content": [
        "By proceeding with the admission application for a student below 18 years of age, I confirm that:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "I am the parent or legally authorised guardian of the student;"
          ]
        },
        {
          "content": [
            "I have read and understood this ",
            {
              "b": "Children's Privacy & Parental Consent Policy"
            },
            ";"
          ]
        },
        {
          "content": [
            "I consent to the collection, use, storage and processing of the student's personal information for legitimate Academy-related purposes;"
          ]
        },
        {
          "content": [
            "I consent to the student's participation in Academy training, activities, tournaments and related programmes, subject to the Academy's applicable rules and policies;"
          ]
        },
        {
          "content": [
            "I understand the provisions relating to photographs and video recordings as described in this Policy; and"
          ]
        },
        {
          "content": [
            "I understand that I may contact the Academy regarding questions, concerns or requests relating to my child's information."
          ]
        }
      ]
    }
  ]
}
