// Generated by scripts/legal_docx_to_ts.py from
// backend/docs_files/ADAMAS CRICKET ACADEMY  GRIEVANCE REDRESSAL POLICY  .docx
// Do not edit by hand — update the .docx and re-run the script.
import type { LegalDocument } from '../types'

export const grievanceContent: LegalDocument = {
  "effectiveDate": null,
  "blocks": [
    {
      "type": "paragraph",
      "content": [
        "Adamas Cricket Academy is committed to providing a professional, safe, respectful and transparent environment for all students, parents/guardians, coaches and stakeholders."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The purpose of this Grievance Redressal Policy is to provide a clear and accessible mechanism through which students, parents/guardians and other stakeholders can raise concerns or complaints relating to the Academy and seek appropriate resolution."
      ]
    },
    {
      "type": "heading",
      "text": "1. Scope"
    },
    {
      "type": "paragraph",
      "content": [
        "This Policy applies to grievances relating to Academy activities and services, including but not limited to:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Admission and registration"
          ]
        },
        {
          "content": [
            "Fees and payments"
          ]
        },
        {
          "content": [
            "Training schedules and batches"
          ]
        },
        {
          "content": [
            "Coaching and training services"
          ]
        },
        {
          "content": [
            "Attendance"
          ]
        },
        {
          "content": [
            "Selection and participation in tournaments"
          ]
        },
        {
          "content": [
            "Academy facilities and infrastructure"
          ]
        },
        {
          "content": [
            "Conduct of Academy staff, coaches or representatives"
          ]
        },
        {
          "content": [
            "Student discipline and behaviour"
          ]
        },
        {
          "content": [
            "Communication and administrative matters"
          ]
        },
        {
          "content": [
            "Safety-related concerns"
          ]
        },
        {
          "content": [
            "Privacy or personal information concerns"
          ]
        },
        {
          "content": [
            "Other matters directly related to the functioning of Adamas Cricket Academy"
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "2. Who Can Raise a Grievance"
    },
    {
      "type": "paragraph",
      "content": [
        "A grievance may be raised by:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "A student enrolled with the Academy"
          ]
        },
        {
          "content": [
            "A parent or legal guardian of a student"
          ]
        },
        {
          "content": [
            "An applicant for admission"
          ]
        },
        {
          "content": [
            "An authorised representative of a student/parent, where appropriate"
          ]
        },
        {
          "content": [
            "Any other stakeholder directly affected by an Academy-related matter"
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "For students below 18 years of age, parents/guardians are encouraged to raise grievances on matters requiring parental involvement."
      ]
    },
    {
      "type": "heading",
      "text": "3. How to Raise a Grievance"
    },
    {
      "type": "paragraph",
      "content": [
        "Grievances should preferably be submitted in writing through the official communication channel of Adamas Cricket Academy."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "A grievance may be submitted by email to:"
      ]
    },
    {
      "type": "paragraph",
      "content": [
        {
          "b": "Email:"
        },
        " cricketacademy@adamasunitedsports.com"
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The grievance should, wherever possible, include:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Name of the student/applicant"
          ]
        },
        {
          "content": [
            "Admission number, if applicable"
          ]
        },
        {
          "content": [
            "Contact details"
          ]
        },
        {
          "content": [
            "Nature of the grievance"
          ]
        },
        {
          "content": [
            "Relevant date, time and location"
          ]
        },
        {
          "content": [
            "Names of persons involved, if relevant"
          ]
        },
        {
          "content": [
            "Supporting documents, photographs or other evidence, if available"
          ]
        },
        {
          "content": [
            "The resolution or action expected from the Academy"
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Providing complete and accurate information will help the Academy investigate and resolve the grievance efficiently."
      ]
    },
    {
      "type": "heading",
      "text": "4. Acknowledgement of Grievance"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy will endeavour to acknowledge receipt of a grievance within ",
        {
          "b": "3 working days"
        },
        " of receiving it."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Where additional information is required, the complainant may be contacted for clarification or supporting documents."
      ]
    },
    {
      "type": "heading",
      "text": "5. Review & Investigation"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Each grievance will be reviewed by the appropriate Academy authority based on the nature and seriousness of the matter."
          ]
        },
        {
          "content": [
            "The Academy may speak with the complainant, student, parent/guardian, coach, staff member or any other relevant person while reviewing the matter."
          ]
        },
        {
          "content": [
            "Relevant documents, records or other available information may be examined."
          ]
        },
        {
          "content": [
            "The Academy will endeavour to maintain fairness and confidentiality during the grievance review process."
          ]
        },
        {
          "content": [
            "Where a grievance involves a particular employee, coach or representative of the Academy, the concerned person may not be responsible for deciding the grievance."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "6. Resolution Timeline"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy will endeavour to resolve grievances within ",
        {
          "b": "15 working days"
        },
        " from receipt of the complete information required to review the matter."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Certain matters may require additional time due to their complexity, involvement of external authorities, tournament regulations, investigation requirements or other circumstances."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Where additional time is required, the complainant may be informed accordingly."
      ]
    },
    {
      "type": "heading",
      "text": "7. Confidentiality"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy will make reasonable efforts to maintain confidentiality of information relating to grievances and the persons involved."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "However, information may be disclosed to authorised persons where reasonably necessary for investigation, resolution, safety, legal compliance or other legitimate institutional purposes."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Complainants are also expected to maintain appropriate confidentiality and avoid sharing confidential grievance-related information publicly while the matter is under review."
      ]
    },
    {
      "type": "heading",
      "text": "8. Urgent & Safety-Related Complaints"
    },
    {
      "type": "paragraph",
      "content": [
        "Any complaint involving an immediate threat to the safety or well-being of a student or any other person should be brought to the immediate attention of Academy management or the responsible campus authority."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Where necessary, the Academy may take immediate preventive or protective measures while the matter is being reviewed."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "In cases involving a medical emergency, serious injury, criminal activity or an immediate safety threat, the appropriate emergency or competent authority may also be contacted."
      ]
    },
    {
      "type": "heading",
      "text": "9. Complaints Involving Minors"
    },
    {
      "type": "paragraph",
      "content": [
        "Where a grievance concerns a student below 18 years of age, the Academy may involve the student's parent/guardian where appropriate."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy will take reasonable steps to ensure that complaints involving minors are handled sensitively and with due regard to the student's safety, dignity and well-being."
      ]
    },
    {
      "type": "heading",
      "text": "10. Protection Against Retaliation"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy does not support retaliation, intimidation or harassment against a person who raises a genuine grievance in good faith."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Any person who believes they have experienced retaliation as a result of raising a genuine grievance should report the matter to Academy management."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "However, knowingly making false, malicious or deliberately misleading complaints may itself be treated as a disciplinary matter."
      ]
    },
    {
      "type": "heading",
      "text": "11. Escalation"
    },
    {
      "type": "paragraph",
      "content": [
        "If the complainant is not satisfied with the response or resolution provided by the Academy, the matter may be escalated to the appropriate senior authority of Adamas United Sports and/or the relevant institutional authority, depending on the nature of the grievance."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy may provide the appropriate escalation channel where required."
      ]
    },
    {
      "type": "heading",
      "text": "12. Matters Outside the Academy's Authority"
    },
    {
      "type": "paragraph",
      "content": [
        "Certain matters may be governed by the rules, regulations or procedures of external organisations, sporting bodies, tournament organisers, educational institutions, government authorities or other competent bodies."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Where applicable, the Academy may guide the complainant towards the appropriate authority or process."
      ]
    },
    {
      "type": "heading",
      "text": "13. Malicious or Frivolous Complaints"
    },
    {
      "type": "paragraph",
      "content": [
        "The grievance mechanism is intended to provide a fair and constructive method for resolving genuine concerns."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Complaints that are knowingly false, malicious, abusive, threatening or repeatedly submitted without reasonable grounds may be subject to appropriate action in accordance with Academy rules and applicable policies."
      ]
    },
    {
      "type": "heading",
      "text": "14. Record Keeping"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy may maintain appropriate records of grievances, communications, investigations and resolutions for administrative, legal, compliance and quality-improvement purposes."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Personal information contained in grievance records will be handled in accordance with the Academy's Privacy Policy and applicable requirements."
      ]
    },
    {
      "type": "heading",
      "text": "15. Policy Updates"
    },
    {
      "type": "paragraph",
      "content": [
        "Adamas Cricket Academy reserves the right to amend or update this Grievance Redressal Policy from time to time based on operational requirements, institutional policies or applicable legal and regulatory requirements."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The latest version may be published through the Academy's admission portal or official communication channels."
      ]
    },
    {
      "type": "heading",
      "text": "GRIEVANCE CONTACT"
    },
    {
      "type": "paragraph",
      "content": [
        {
          "b": "Adamas Cricket Academy"
        },
        {
          "br": true
        },
        {
          "b": "Adamas United Sports"
        },
        {
          "br": true
        },
        "Adamas Knowledge City, Barasat, West Bengal, India"
      ]
    },
    {
      "type": "paragraph",
      "content": [
        {
          "b": "Email:"
        },
        " cricketacademy@adamasunitedsports.com"
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "For urgent safety or emergency matters, the complainant should immediately contact the Academy management/campus authority rather than wait for the normal grievance process."
      ]
    },
    {
      "type": "heading",
      "text": "ACKNOWLEDGEMENT"
    },
    {
      "type": "paragraph",
      "content": [
        "By proceeding with the admission application, the applicant/parent/guardian acknowledges that they have read and understood the ",
        {
          "b": "Grievance Redressal Policy of Adamas Cricket Academy"
        },
        " and understand the mechanism available for raising Academy-related concerns or complaints."
      ]
    }
  ]
}
