// Generated by scripts/legal_docx_to_ts.py from
// backend/docs_files/ADAMAS CRICKET ACADEMY  PRIVACY POLICY .docx
// Do not edit by hand — update the .docx and re-run the script.
import type { LegalDocument } from '../types'

export const privacyContent: LegalDocument = {
  "effectiveDate": "5 October 2026",
  "blocks": [
    {
      "type": "paragraph",
      "content": [
        "Adamas Cricket Academy (“Academy”, “we”, “us” or “our”) respects the privacy of its students, applicants, parents/guardians and other users of its admission portal and services."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "This Privacy Policy explains how we collect, use, store, process and protect personal information provided during the admission process and in connection with participation in the activities and programmes of Adamas Cricket Academy."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "By submitting an application through the Academy's admission portal and providing consent to this Privacy Policy, the applicant and/or parent/guardian acknowledges that they have read and understood how their information may be collected and used as described below."
      ]
    },
    {
      "type": "heading",
      "text": "1. Information We Collect"
    },
    {
      "type": "paragraph",
      "content": [
        "Depending on the nature of the application and services, we may collect the following information:"
      ]
    },
    {
      "type": "subheading",
      "text": "A. Student Information"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Full name"
          ]
        },
        {
          "content": [
            "Date of birth"
          ]
        },
        {
          "content": [
            "Age and age group"
          ]
        },
        {
          "content": [
            "Gender"
          ]
        },
        {
          "content": [
            "Photograph"
          ]
        },
        {
          "content": [
            "Residential address"
          ]
        },
        {
          "content": [
            "School/educational institution details"
          ]
        },
        {
          "content": [
            "Cricket playing experience and achievements"
          ]
        },
        {
          "content": [
            "Previous tournament/competition details"
          ]
        },
        {
          "content": [
            "Trial and assessment information"
          ]
        },
        {
          "content": [
            "Training and attendance records"
          ]
        },
        {
          "content": [
            "Academy admission and membership details"
          ]
        }
      ]
    },
    {
      "type": "subheading",
      "text": "B. Parent/Guardian Information"
    },
    {
      "type": "paragraph",
      "content": [
        "For students below 18 years of age, we may collect:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Parent/guardian name"
          ]
        },
        {
          "content": [
            "Relationship with the student"
          ]
        },
        {
          "content": [
            "Mobile number"
          ]
        },
        {
          "content": [
            "Email address"
          ]
        },
        {
          "content": [
            "Residential/contact address"
          ]
        },
        {
          "content": [
            "Emergency contact information"
          ]
        }
      ]
    },
    {
      "type": "subheading",
      "text": "C. Payment & Transaction Information"
    },
    {
      "type": "paragraph",
      "content": [
        "We may collect information relating to admission fees, coaching fees and other Academy-related payments, including transaction details necessary to verify and maintain payment records."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Where payments are processed through third-party payment gateways or financial institutions, payment information may be processed directly by those service providers in accordance with their respective privacy policies."
      ]
    },
    {
      "type": "subheading",
      "text": "D. Other Information"
    },
    {
      "type": "paragraph",
      "content": [
        "We may also collect information relating to:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Participation in Academy activities"
          ]
        },
        {
          "content": [
            "Tournament participation"
          ]
        },
        {
          "content": [
            "Fitness and training assessments"
          ]
        },
        {
          "content": [
            "Feedback and communication"
          ]
        },
        {
          "content": [
            "Requests, enquiries and complaints"
          ]
        },
        {
          "content": [
            "Photographs and video recordings"
          ]
        },
        {
          "content": [
            "Information required for tournament registration, affiliation or participation"
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "2. How We Use Personal Information"
    },
    {
      "type": "paragraph",
      "content": [
        "The information collected may be used for legitimate Academy-related purposes, including:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Processing and managing admission applications."
          ]
        },
        {
          "content": [
            "Creating and maintaining student records."
          ]
        },
        {
          "content": [
            "Managing training batches, schedules and attendance."
          ]
        },
        {
          "content": [
            "Collecting and maintaining records of fees and payments."
          ]
        },
        {
          "content": [
            "Communicating with students and parents/guardians."
          ]
        },
        {
          "content": [
            "Organising training programmes, camps, tournaments and events."
          ]
        },
        {
          "content": [
            "Managing player selection and participation in competitions."
          ]
        },
        {
          "content": [
            "Maintaining emergency and contact information."
          ]
        },
        {
          "content": [
            "Providing appropriate support during Academy activities."
          ]
        },
        {
          "content": [
            "Complying with applicable legal, regulatory, institutional and sporting requirements."
          ]
        },
        {
          "content": [
            "Preparing internal reports, statistics and operational records."
          ]
        },
        {
          "content": [
            "Improving Academy programmes, services and student experience."
          ]
        },
        {
          "content": [
            "Promoting Academy activities, achievements, events and programmes through authorised communication channels."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "3. Photographs & Video Recordings"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy may photograph or record students during training sessions, matches, tournaments, camps, events and other Academy-related activities."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Such photographs and recordings may be used for legitimate Academy-related purposes, including:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Academy website"
          ]
        },
        {
          "content": [
            "Social media platforms"
          ]
        },
        {
          "content": [
            "Digital and print promotional materials"
          ]
        },
        {
          "content": [
            "Brochures and publications"
          ]
        },
        {
          "content": [
            "News and media coverage"
          ]
        },
        {
          "content": [
            "Event documentation"
          ]
        },
        {
          "content": [
            "Academy reports and presentations"
          ]
        },
        {
          "content": [
            "Promotion of student and Academy achievements"
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "For students below 18 years of age, the relevant consent will be obtained from the parent/guardian through the admission process."
      ]
    },
    {
      "type": "heading",
      "text": "4. Information Relating to Minors"
    },
    {
      "type": "paragraph",
      "content": [
        "Adamas Cricket Academy may provide programmes and services to students below 18 years of age."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Where the student is a minor, information may be collected and processed with the consent and involvement of the parent or legal guardian."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Parents/guardians are responsible for ensuring that the information provided about the student is accurate and complete and for notifying the Academy of any relevant changes."
      ]
    },
    {
      "type": "heading",
      "text": "5. Sharing of Information"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy will not ordinarily sell or commercially trade personal information of students or parents/guardians."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Personal information may, however, be shared with authorised persons or organisations where reasonably necessary for legitimate Academy-related purposes, including:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Adamas University and/or associated institutional entities, where applicable"
          ]
        },
        {
          "content": [
            "Academy management and authorised employees"
          ]
        },
        {
          "content": [
            "Coaches and authorised support staff"
          ]
        },
        {
          "content": [
            "Tournament and sporting authorities"
          ]
        },
        {
          "content": [
            "Affiliated sports associations and governing bodies"
          ]
        },
        {
          "content": [
            "Event organisers"
          ]
        },
        {
          "content": [
            "Service providers supporting Academy operations"
          ]
        },
        {
          "content": [
            "Payment gateway and financial service providers"
          ]
        },
        {
          "content": [
            "Technology, hosting and software service providers"
          ]
        },
        {
          "content": [
            "Medical or emergency service providers where necessary"
          ]
        },
        {
          "content": [
            "Government, regulatory or law-enforcement authorities where legally required"
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Only information reasonably necessary for the relevant purpose should be shared wherever practicable."
      ]
    },
    {
      "type": "heading",
      "text": "6. Data Security"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy takes reasonable administrative, technical and organisational measures to protect personal information against unauthorised access, misuse, alteration, disclosure, loss or destruction."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "However, no method of electronic transmission or storage can be guaranteed to be completely secure. Accordingly, while the Academy takes reasonable precautions to protect information, absolute security cannot be guaranteed."
      ]
    },
    {
      "type": "heading",
      "text": "7. Data Retention"
    },
    {
      "type": "paragraph",
      "content": [
        "Personal information may be retained for as long as reasonably necessary to:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Provide Academy services"
          ]
        },
        {
          "content": [
            "Maintain student and admission records"
          ]
        },
        {
          "content": [
            "Maintain financial and payment records"
          ]
        },
        {
          "content": [
            "Fulfil legal, regulatory and institutional requirements"
          ]
        },
        {
          "content": [
            "Resolve disputes or complaints"
          ]
        },
        {
          "content": [
            "Maintain appropriate records of Academy activities"
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "When personal information is no longer required for legitimate purposes, it may be deleted, anonymised or securely disposed of in accordance with applicable requirements and the Academy's record-retention practices."
      ]
    },
    {
      "type": "heading",
      "text": "8. Communication"
    },
    {
      "type": "paragraph",
      "content": [
        "By providing contact information, applicants and parents/guardians may receive communications relating to:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Admission status"
          ]
        },
        {
          "content": [
            "Training schedules"
          ]
        },
        {
          "content": [
            "Fee reminders"
          ]
        },
        {
          "content": [
            "Academy activities"
          ]
        },
        {
          "content": [
            "Tournaments and competitions"
          ]
        },
        {
          "content": [
            "Events and camps"
          ]
        },
        {
          "content": [
            "Important operational announcements"
          ]
        },
        {
          "content": [
            "Other information directly related to the student's participation in the Academy"
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Such communication may be sent through email, telephone, SMS, WhatsApp or other authorised communication channels."
      ]
    },
    {
      "type": "heading",
      "text": "9. Third-Party Websites, Services & Payment Platforms"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy may use third-party technology platforms, payment gateways, communication services, hosting providers and other service providers as part of its operations."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Where an applicant uses a third-party service through or in connection with the Academy's admission portal, the processing of information by that third party may also be subject to the third party's own terms and privacy policy."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy does not control the privacy practices of independent third-party service providers."
      ]
    },
    {
      "type": "heading",
      "text": "10. Cookies & Technical Information"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy's website or admission portal may use cookies, log files or similar technologies to support website functionality, security, user experience and operational analysis."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Technical information such as browser type, device information, IP address, access time and usage information may be collected automatically where applicable."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Such information may be used for security, troubleshooting, analytics and improving the performance of the portal."
      ]
    },
    {
      "type": "heading",
      "text": "11. Accuracy of Information"
    },
    {
      "type": "paragraph",
      "content": [
        "Applicants and parents/guardians are responsible for providing accurate, complete and updated information."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "If any information changes after admission, the applicant/parent/guardian should notify the Academy through the appropriate communication channel so that records can be updated where applicable."
      ]
    },
    {
      "type": "heading",
      "text": "12. Data Rights & Requests"
    },
    {
      "type": "paragraph",
      "content": [
        "Subject to applicable laws and institutional policies, individuals may request information regarding the personal data held about them and may request correction or updating of inaccurate information."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Requests relating to personal information may be submitted to the Academy using the official contact details provided on the Academy's website or admission portal."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy may require reasonable verification of the identity of the person making such a request before processing it."
      ]
    },
    {
      "type": "heading",
      "text": "13. Withdrawal of Consent"
    },
    {
      "type": "paragraph",
      "content": [
        "Where consent is the legal basis for a particular use of personal information, the applicant or parent/guardian may request withdrawal of such consent, subject to applicable legal, contractual and operational requirements."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Withdrawal of consent may affect the Academy's ability to provide certain services or allow participation in specific activities where the relevant information or consent is necessary."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Withdrawal of consent will not affect processing that was lawfully carried out before the withdrawal."
      ]
    },
    {
      "type": "heading",
      "text": "14. Changes to this Privacy Policy"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy may update this Privacy Policy from time to time to reflect changes in its operations, technology, legal requirements or institutional policies."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The updated Privacy Policy may be published on the Academy's admission portal or official communication channels."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Applicants and parents/guardians are encouraged to review the Privacy Policy periodically."
      ]
    },
    {
      "type": "heading",
      "text": "15. Contact"
    },
    {
      "type": "paragraph",
      "content": [
        "For questions, concerns or requests relating to this Privacy Policy or the handling of personal information, applicants/parents/guardians may contact:"
      ]
    },
    {
      "type": "paragraph",
      "content": [
        {
          "b": "Adamas Cricket Academy"
        },
        {
          "br": true
        },
        "Adamas United Sports",
        {
          "br": true
        },
        "Adamas Knowledge City, Barasat, West Bengal, India"
      ]
    },
    {
      "type": "paragraph",
      "content": [
        {
          "b": "Email:"
        },
        " cricketacademy@adamasunitedsports.com"
      ]
    },
    {
      "type": "heading",
      "text": "PRIVACY CONSENT"
    },
    {
      "type": "paragraph",
      "content": [
        "By proceeding with the admission application, the applicant/parent/guardian confirms that they have read and understood this Privacy Policy and consent to the collection, use, storage and processing of personal information as described above for legitimate Academy-related purposes."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        {
          "b": "I have read, understood and agree to the Privacy Policy of Adamas Cricket Academy."
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        {
          "b": "For applicants below 18 years of age, this consent must be provided by the parent/guardian."
        }
      ]
    }
  ]
}
