// Generated by scripts/legal_docx_to_ts.py from
// backend/docs_files/ADAMAS CRICKET ACADEMY  REFUND & CANCELLATION POLICY  .docx
// Do not edit by hand — update the .docx and re-run the script.
import type { LegalDocument } from '../types'

export const refundContent: LegalDocument = {
  "effectiveDate": null,
  "blocks": [
    {
      "type": "paragraph",
      "content": [
        "This Refund & Cancellation Policy applies to all admissions, registrations, coaching fees, training programmes and other paid services provided by ",
        {
          "b": "Adamas Cricket Academy"
        },
        "."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "By completing the admission process and making payment, the applicant and/or parent/guardian acknowledges that they have read, understood and agreed to this Policy."
      ]
    },
    {
      "type": "heading",
      "text": "1. Admission / Registration Fee"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "The admission/registration fee paid at the time of enrolment is ",
            {
              "b": "non-refundable and non-transferable"
            },
            " once the admission has been confirmed."
          ]
        },
        {
          "content": [
            "If an applicant voluntarily withdraws after admission has been confirmed, the admission/registration fee will not ordinarily be refunded."
          ]
        },
        {
          "content": [
            "The admission/registration fee cannot be transferred to another student or another batch without specific written approval from the Academy."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "2. Monthly Coaching Fees"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Monthly coaching fees are payable in advance as per the applicable fee structure."
          ]
        },
        {
          "content": [
            "Once a monthly coaching fee has been paid, it is ",
            {
              "b": "non-refundable and non-transferable"
            },
            "."
          ]
        },
        {
          "content": [
            "No refund or fee adjustment will ordinarily be provided for:"
          ],
          "children": [
            [
              "Absence from training"
            ],
            [
              "Personal reasons"
            ],
            [
              "Holidays or travel"
            ],
            [
              "School/college examinations"
            ],
            [
              "Temporary illness or injury"
            ],
            [
              "Change of personal plans"
            ],
            [
              "Failure to attend scheduled sessions"
            ]
          ]
        },
        {
          "content": [
            "A student cannot carry forward unused training sessions from one month to another unless specifically approved by the Academy."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "3. Cancellation Before Commencement of Training"
    },
    {
      "type": "paragraph",
      "content": [
        "If an applicant requests cancellation before the student's training has commenced, the Academy may consider the request on a case-by-case basis."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Any refund, if approved, will be subject to deduction of applicable administrative, processing or other charges."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The admission/registration fee will ordinarily remain non-refundable."
      ]
    },
    {
      "type": "heading",
      "text": "4. Cancellation After Commencement of Training"
    },
    {
      "type": "paragraph",
      "content": [
        "Once training has commenced, cancellation by the student/parent/guardian will generally ",
        {
          "b": "not qualify for a refund of fees already paid"
        },
        "."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Any exception will be considered solely at the discretion of the Academy based on the circumstances of the case."
      ]
    },
    {
      "type": "heading",
      "text": "5. Academy-Initiated Cancellation or Suspension"
    },
    {
      "type": "paragraph",
      "content": [
        "If the Academy is required to cancel or discontinue a programme permanently due to operational, administrative, infrastructure, regulatory or other circumstances, the Academy may, at its discretion:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Provide an alternative training arrangement;"
          ]
        },
        {
          "content": [
            "Reschedule the programme;"
          ]
        },
        {
          "content": [
            "Transfer the student to another available batch; or"
          ]
        },
        {
          "content": [
            "Provide an appropriate refund or adjustment, where considered applicable."
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The nature and amount of any refund or adjustment will depend on the circumstances and services already provided."
      ]
    },
    {
      "type": "heading",
      "text": "6. Cancellation of Individual Training Sessions"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "The Academy may cancel, postpone or reschedule individual training sessions due to:"
          ],
          "children": [
            [
              "Adverse weather conditions"
            ],
            [
              "Ground or facility issues"
            ],
            [
              "Tournaments or competitions"
            ],
            [
              "Maintenance"
            ],
            [
              "Institutional events"
            ],
            [
              "Safety concerns"
            ],
            [
              "Unforeseen circumstances"
            ]
          ]
        },
        {
          "content": [
            "Where a session is cancelled by the Academy, the Academy may provide a replacement session or alternative arrangement at its discretion."
          ]
        },
        {
          "content": [
            "Cancellation of an individual session will not automatically entitle the student to a refund or reduction in monthly fees."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "7. Medical Reasons"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Temporary illness, injury or medical absence will not ordinarily qualify for a refund or fee adjustment."
          ]
        },
        {
          "content": [
            "Where a student is medically advised to discontinue training for an extended period, the parent/guardian may submit a written request along with appropriate supporting medical documentation."
          ]
        },
        {
          "content": [
            "Any fee adjustment or other consideration in such cases will be entirely at the discretion of the Academy."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "8. Transfer of Admission"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Admission and paid fees are generally non-transferable from one student to another."
          ]
        },
        {
          "content": [
            "Transfer to another batch, programme or branch, where available, may be considered subject to availability and approval by the Academy."
          ]
        },
        {
          "content": [
            "Any applicable difference in fees or additional charges will be payable as required."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "9. Refund Processing"
    },
    {
      "type": "paragraph",
      "content": [
        "Where a refund is approved by the Academy:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "The refund will generally be processed through the original payment method or another method determined by the Academy."
          ]
        },
        {
          "content": [
            "Applicable payment gateway, banking, transaction or administrative charges may be deducted where applicable."
          ]
        },
        {
          "content": [
            "Refund processing may take reasonable time depending on the payment method and financial institution."
          ]
        },
        {
          "content": [
            "The Academy will not be responsible for delays caused by banks, payment gateways or other third-party payment service providers."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "10. Duplicate or Excess Payments"
    },
    {
      "type": "paragraph",
      "content": [
        "If a student/parent/guardian makes a duplicate payment or pays an amount in excess of the applicable fee by mistake, the excess amount may be refunded or adjusted against future applicable fees after verification by the Academy."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Any applicable transaction or processing charges may be deducted where relevant."
      ]
    },
    {
      "type": "heading",
      "text": "11. Non-Payment of Fees"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Fees must be paid within the prescribed payment deadline."
          ]
        },
        {
          "content": [
            "A late fee may be applicable for delayed payment as communicated by the Academy."
          ]
        },
        {
          "content": [
            "Continued non-payment may result in suspension of training or cancellation of admission."
          ]
        },
        {
          "content": [
            "Cancellation or suspension due to non-payment does not create an automatic entitlement to a refund of previously paid fees."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "12. Refund for Additional Activities"
    },
    {
      "type": "paragraph",
      "content": [
        "Fees paid separately for tournaments, camps, events, travel, accommodation, uniforms, equipment or other special activities may be subject to separate refund and cancellation terms communicated for the relevant activity."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Where an external organiser, tournament authority, travel provider or other third party determines its own cancellation/refund terms, the applicable third-party policy may also apply."
      ]
    },
    {
      "type": "heading",
      "text": "13. Exceptional Circumstances"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy may consider refund or adjustment requests arising from exceptional circumstances on a ",
        {
          "b": "case-by-case basis"
        },
        "."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Such consideration does not create an automatic right to a refund and will depend on the specific facts, supporting documents and services already provided."
      ]
    },
    {
      "type": "heading",
      "text": "14. How to Request Cancellation or Refund"
    },
    {
      "type": "paragraph",
      "content": [
        "Requests for cancellation or refund should be submitted in writing to:"
      ]
    },
    {
      "type": "paragraph",
      "content": [
        {
          "b": "Email:"
        },
        " cricketacademy@adamasunitedsports.com"
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The request should include:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Student's full name"
          ]
        },
        {
          "content": [
            "Admission number, if applicable"
          ]
        },
        {
          "content": [
            "Parent/guardian name"
          ]
        },
        {
          "content": [
            "Registered mobile number"
          ]
        },
        {
          "content": [
            "Payment details"
          ]
        },
        {
          "content": [
            "Date and amount of payment"
          ]
        },
        {
          "content": [
            "Reason for cancellation/refund request"
          ]
        },
        {
          "content": [
            "Supporting documents, where applicable"
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy may request additional information before processing the request."
      ]
    },
    {
      "type": "heading",
      "text": "15. Final Decision"
    },
    {
      "type": "paragraph",
      "content": [
        "All refund and cancellation requests will be reviewed in accordance with this Policy."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Where an exception is requested, the decision of the authorised Academy management shall be final, subject to applicable laws, regulations and institutional policies."
      ]
    },
    {
      "type": "heading",
      "text": "16. Changes to the Policy"
    },
    {
      "type": "paragraph",
      "content": [
        "Adamas Cricket Academy reserves the right to amend or update this Refund & Cancellation Policy from time to time."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The latest version may be published on the Academy's admission portal or through its official communication channels."
      ]
    },
    {
      "type": "heading",
      "text": "ACKNOWLEDGEMENT"
    },
    {
      "type": "paragraph",
      "content": [
        "By proceeding with the admission application and making payment, the applicant/parent/guardian confirms that they have read, understood and agreed to the ",
        {
          "b": "Refund & Cancellation Policy of Adamas Cricket Academy"
        },
        "."
      ]
    }
  ]
}
