// Generated by scripts/legal_docx_to_ts.py from
// backend/docs_files/ADAMAS CRICKET ACADEMY_TERMS & CONDITIONS  .docx
// Do not edit by hand — update the .docx and re-run the script.
import type { LegalDocument } from '../types'

export const termsContent: LegalDocument = {
  "effectiveDate": null,
  "blocks": [
    {
      "type": "paragraph",
      "content": [
        "These Terms & Conditions govern the admission, participation and use of the facilities and services provided by ",
        {
          "b": "Adamas Cricket Academy"
        },
        ". By submitting an application for admission, the applicant and/or parent/guardian is deemed to have read, understood and agreed to comply with these Terms & Conditions."
      ]
    },
    {
      "type": "heading",
      "text": "1. Admission"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Admission to Adamas Cricket Academy is subject to availability of seats and fulfilment of the eligibility criteria prescribed by the Academy."
          ]
        },
        {
          "content": [
            "The Academy reserves the right to conduct trials, assessments or evaluations as part of the admission or training process."
          ]
        },
        {
          "content": [
            "Submission of an admission application does not guarantee admission. The Academy reserves the right to accept or reject an application based on its admission criteria, age group, playing level, availability of seats and other relevant considerations."
          ]
        },
        {
          "content": [
            "All information submitted during the admission process must be true, accurate and complete. The Academy reserves the right to cancel admission if any information is found to be false, incomplete or misleading."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "2. Fees & Payment"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Admission fees and monthly coaching fees shall be payable as per the fee structure communicated by the Academy."
          ]
        },
        {
          "content": [
            "Monthly coaching fees must be paid on or before the ",
            {
              "b": "10th of every month"
            },
            ", unless otherwise communicated by the Academy."
          ]
        },
        {
          "content": [
            "A ",
            {
              "b": "late fee of ₹500/-"
            },
            " may be charged for payments made after the prescribed due date."
          ]
        },
        {
          "content": [
            "Fees once paid are generally ",
            {
              "b": "non-refundable and non-transferable"
            },
            ", except where specifically approved by the Academy."
          ]
        },
        {
          "content": [
            "Absence from training due to personal reasons, holidays, examinations, travel, illness or any other reason will not ordinarily entitle the student to a fee refund, adjustment or waiver."
          ]
        },
        {
          "content": [
            "The Academy reserves the right to revise its fee structure from time to time. Any applicable revision will be communicated to the students/parents."
          ]
        },
        {
          "content": [
            "Any additional charges relating to tournaments, travel, special camps, uniforms, equipment, accommodation or other activities will be communicated separately and shall be payable as applicable."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "3. Training & Attendance"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Students are expected to attend all scheduled training sessions regularly and punctually."
          ]
        },
        {
          "content": [
            "Students must follow the training schedule and instructions issued by the Academy and its coaching staff."
          ]
        },
        {
          "content": [
            "Regular attendance and punctuality may be considered while selecting players for matches, tournaments and other competitive opportunities."
          ]
        },
        {
          "content": [
            "The Academy may change training timings, schedules, venues or programmes due to weather conditions, ground conditions, tournaments, maintenance, institutional requirements or other operational reasons."
          ]
        },
        {
          "content": [
            "In case a training session is cancelled by the Academy, the Academy may reschedule the session or make an alternative arrangement at its discretion."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "4. Discipline & Code of Conduct"
    },
    {
      "type": "paragraph",
      "content": [
        "Students are expected to maintain proper discipline and behave respectfully towards coaches, staff, fellow students, officials, visitors and members of opposing teams."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "The following conduct will not be permitted:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Abusive, threatening or inappropriate language or behaviour"
          ]
        },
        {
          "content": [
            "Fighting, bullying, harassment or intimidation"
          ]
        },
        {
          "content": [
            "Disrespectful behaviour towards coaches, staff or other students"
          ]
        },
        {
          "content": [
            "Deliberate damage to Academy, university or other property"
          ]
        },
        {
          "content": [
            "Theft or unauthorised use of another person's belongings"
          ]
        },
        {
          "content": [
            "Possession or use of prohibited substances or items"
          ]
        },
        {
          "content": [
            "Any behaviour that may adversely affect the reputation or interests of Adamas Cricket Academy or its affiliated institutions"
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Depending on the seriousness of the violation, the Academy may issue a warning, suspend training privileges or terminate the student's admission."
      ]
    },
    {
      "type": "heading",
      "text": "5. Selection for Teams & Tournaments"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Admission to Adamas Cricket Academy does not guarantee selection for any Academy team, tournament, league, school/university competition or representative team."
          ]
        },
        {
          "content": [
            "Selection will be based on factors including playing performance, skill level, fitness, discipline, attendance, eligibility, team requirements and other sporting considerations."
          ]
        },
        {
          "content": [
            "Selection decisions made by the designated coaching/selection authority shall be treated as final."
          ]
        },
        {
          "content": [
            "Students selected for tournaments or competitions may be required to fulfil additional eligibility, documentation, registration and financial requirements."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "6. Cricket Equipment & Uniform"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Students are required to attend training in appropriate sportswear, footwear and the prescribed Academy uniform/kit, wherever applicable."
          ]
        },
        {
          "content": [
            "Students may be required to purchase prescribed Academy jerseys, uniforms, training kits or other equipment separately."
          ]
        },
        {
          "content": [
            "Students are responsible for their personal cricket equipment and belongings brought to the Academy."
          ]
        },
        {
          "content": [
            "The Academy shall not ordinarily be responsible for loss, theft or damage to personal belongings."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "7. Health, Fitness & Medical Information"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Parents/guardians are responsible for informing the Academy about any relevant medical condition, injury, allergy, medication requirement or physical limitation that may affect the student's participation in training or sporting activities."
          ]
        },
        {
          "content": [
            "Students should not participate in training if they are medically unfit or if participation may pose a risk to themselves or others."
          ]
        },
        {
          "content": [
            "The Academy may restrict or discontinue a student's participation in any activity if the coaching or management team considers it necessary for the student's safety."
          ]
        },
        {
          "content": [
            "In the event of an injury or medical emergency during an Academy activity, the Academy may provide basic first aid and/or arrange necessary medical assistance."
          ]
        },
        {
          "content": [
            "Parents/guardians acknowledge that cricket and physical training involve inherent risks of injury and agree that the student will participate responsibly and follow all safety instructions issued by the Academy."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "8. Use of Facilities & Academy Property"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Students must use Academy and campus facilities responsibly and follow all instructions relating to safety and facility usage."
          ]
        },
        {
          "content": [
            "Any intentional or negligent damage to Academy, university or campus property may result in recovery of the repair or replacement cost from the student/parent/guardian."
          ]
        },
        {
          "content": [
            "Access to certain facilities may be restricted due to maintenance, events, tournaments, training schedules or other operational requirements."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "9. Photography, Video & Media Consent"
    },
    {
      "type": "paragraph",
      "content": [
        "Students may be photographed or recorded during Academy training sessions, matches, tournaments, camps, events and other Academy-related activities."
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Such photographs and videos may be used by Adamas Cricket Academy and/or its authorised representatives for legitimate Academy-related purposes, including:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Website and social media"
          ]
        },
        {
          "content": [
            "Promotional and marketing materials"
          ]
        },
        {
          "content": [
            "Academy brochures and publications"
          ]
        },
        {
          "content": [
            "News and media coverage"
          ]
        },
        {
          "content": [
            "Internal reports and presentations"
          ]
        },
        {
          "content": [
            "Documentation of Academy activities and achievements"
          ]
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        "Where the applicant is a minor, consent given by the parent/guardian shall apply on behalf of the student."
      ]
    },
    {
      "type": "heading",
      "text": "10. Communication"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "The Academy may communicate with students and/or parents/guardians through WhatsApp, SMS, email, telephone, notices, the admission portal or other official communication channels."
          ]
        },
        {
          "content": [
            "Applicants are responsible for providing accurate and updated contact details."
          ]
        },
        {
          "content": [
            "Students and parents/guardians are expected to regularly check official Academy communications regarding training, fees, holidays, tournaments, events and other important information."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "11. Leave & Absence"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Students/parents should inform the Academy or coaching staff in advance wherever possible in case of absence."
          ]
        },
        {
          "content": [
            "Extended or frequent absence may affect the student's training progress and eligibility for selection in matches or tournaments."
          ]
        },
        {
          "content": [
            "Absence from training does not ordinarily entitle the student to a fee refund, adjustment or waiver."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "12. Withdrawal & Termination"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "A student wishing to discontinue training may be required to inform the Academy through the prescribed process."
          ]
        },
        {
          "content": [
            "Fees already paid will generally not be refundable or transferable."
          ]
        },
        {
          "content": [
            "The Academy reserves the right to suspend or terminate a student's admission in cases including, but not limited to:"
          ],
          "children": [
            [
              "Serious misconduct or disciplinary violations"
            ],
            [
              "Repeated violation of Academy rules"
            ],
            [
              "Non-payment of applicable fees"
            ],
            [
              "Submission of false or misleading information"
            ],
            [
              "Damage to Academy/institutional property"
            ],
            [
              "Behaviour that adversely affects the safety, discipline or reputation of the Academy"
            ]
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "13. Changes to Training Programme"
    },
    {
      "type": "paragraph",
      "content": [
        "The Academy reserves the right to modify training schedules, coaching arrangements, programmes, facilities, venues, batches, coaches or other operational arrangements based on administrative, sporting, safety, infrastructure or other requirements."
      ]
    },
    {
      "type": "heading",
      "text": "14. Parent/Guardian Responsibility"
    },
    {
      "type": "paragraph",
      "content": [
        "For students below 18 years of age, the parent/guardian is responsible for:"
      ]
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "Providing accurate information during the admission process."
          ]
        },
        {
          "content": [
            "Ensuring timely payment of applicable fees."
          ]
        },
        {
          "content": [
            "Supporting regular attendance and punctuality."
          ]
        },
        {
          "content": [
            "Ensuring that the student follows Academy rules and instructions."
          ]
        },
        {
          "content": [
            "Informing the Academy about relevant medical or other circumstances that may affect the student's participation."
          ]
        },
        {
          "content": [
            "Cooperating with the Academy in matters relating to training, discipline, tournaments and the overall development of the student."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "15. General"
    },
    {
      "type": "list",
      "items": [
        {
          "content": [
            "These Terms & Conditions shall be applicable to all students enrolled with Adamas Cricket Academy."
          ]
        },
        {
          "content": [
            "The Academy reserves the right to interpret and implement these Terms & Conditions in the interest of the Academy, its students and the safe and effective conduct of its programmes."
          ]
        },
        {
          "content": [
            "Any matter not specifically covered under these Terms & Conditions shall be decided by the Academy management."
          ]
        },
        {
          "content": [
            "The Academy reserves the right to amend or update these Terms & Conditions from time to time. The updated Terms & Conditions may be published through the Academy's official communication channels or admission portal."
          ]
        }
      ]
    },
    {
      "type": "heading",
      "text": "CONSENT"
    },
    {
      "type": "paragraph",
      "content": [
        {
          "b": "By proceeding with the admission application, the applicant/parent/guardian confirms that they have read, understood and agreed to the above Terms & Conditions of Adamas Cricket Academy and agree to abide by the rules, policies and instructions of the Academy."
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        {
          "b": "For applicants below 18 years of age, this consent must be provided by the parent/guardian."
        }
      ]
    }
  ]
}
