# Generated by Django 5.1.15 on 2026-09-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionpayment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
