# Generated by Django 5.1.15 on 2026-09-17 16:43

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_paymenttype"),
        ("payment", "0002_admissionpayment_idempotency_key"),
        ("people", "0002_guardian_staff_studentguardian"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("billing_period", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("upi", "UPI"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("online_transfer", "Online transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_no", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("settled", "Settled"),
                            ("void", "Void"),
                        ],
                        db_index=True,
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("confirmation_no", models.CharField(max_length=20, unique=True)),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                ("invoice_no", models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ("invoiced_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(blank=True, db_index=True, max_length=255)),
                (
                    "payment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.paymenttype",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="people.person",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "settled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("billing_period__isnull", False)),
                        fields=("person", "payment_type", "billing_period"),
                        name="unique_person_payment_type_period",
                    )
                ],
            },
        ),
    ]
