# Generated by Django 5.1.15 on 2026-08-31 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("read", "Read"),
                            ("export", "Export"),
                            ("login", "Login"),
                            ("approve", "Approve"),
                        ],
                        max_length=10,
                    ),
                ),
                ("model_label", models.CharField(help_text="app_label.ModelName", max_length=150)),
                ("object_id", models.CharField(max_length=64)),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, help_text='{field: {"from": x, "to": y}}'
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=36)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for system actions (Celery beat, migrations).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["model_label", "object_id"], name="audit_audit_model_l_b619eb_idx"
                    ),
                    models.Index(
                        fields=["actor", "created_at"], name="audit_audit_actor_i_ec0f72_idx"
                    ),
                ],
            },
        ),
    ]
