# Generated by Django 5.1.15 on 2026-09-18 07:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                            ("leave", "Leave"),
                            ("medical_leave", "Medical leave"),
                            ("tournament_duty", "Tournament duty"),
                            ("official_duty", "Official duty"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                            ("leave", "Leave"),
                            ("medical_leave", "Medical leave"),
                            ("tournament_duty", "Tournament duty"),
                            ("official_duty", "Official duty"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                            ("leave", "Leave"),
                            ("medical_leave", "Medical leave"),
                            ("tournament_duty", "Tournament duty"),
                            ("official_duty", "Official duty"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
