# Generated by Django 5.1.15 on 2026-09-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialresult',
            name='outcome',
            field=models.CharField(choices=[('selected', 'Selected'), ('shortlisted', 'Shortlisted'), ('waitlisted', 'Waitlisted'), ('not_selected', 'Not selected'), ('re_trial', 'Re-trial')], db_index=True, max_length=20),
        ),
    ]
