# Generated by Django 5.1.15 on 2026-08-26 12:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0002_initial"),
        ("core", "0004_agecategory_assessmentcriterion_documenttype_and_more"),
        ("people", "0002_guardian_staff_studentguardian"),
        ("student", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="admission.admission",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="admission_date",
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name="student",
            name="completed_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="programme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="core.programme",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="residential",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("enquiry", "Enquiry"),
                    ("trial", "Trial"),
                    ("selected", "Selected"),
                    ("admission_pending", "Admission pending"),
                    ("active", "Active"),
                    ("medical_hold", "Medical hold"),
                    ("fee_hold", "Fee hold"),
                    ("leave", "Leave"),
                    ("suspended", "Suspended"),
                    ("withdrawn", "Withdrawn"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="withdrawn_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="StudentStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("enquiry", "Enquiry"),
                            ("trial", "Trial"),
                            ("selected", "Selected"),
                            ("admission_pending", "Admission pending"),
                            ("active", "Active"),
                            ("medical_hold", "Medical hold"),
                            ("fee_hold", "Fee hold"),
                            ("leave", "Leave"),
                            ("suspended", "Suspended"),
                            ("withdrawn", "Withdrawn"),
                            ("completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("enquiry", "Enquiry"),
                            ("trial", "Trial"),
                            ("selected", "Selected"),
                            ("admission_pending", "Admission pending"),
                            ("active", "Active"),
                            ("medical_hold", "Medical hold"),
                            ("fee_hold", "Fee hold"),
                            ("leave", "Leave"),
                            ("suspended", "Suspended"),
                            ("withdrawn", "Withdrawn"),
                            ("completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.approvalrequest",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
