# Generated by Django 5.1.15 on 2026-08-31 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_guardian_staff_studentguardian"),
        ("student", "0002_student_admission_student_admission_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="people.person",
            ),
        ),
    ]
