# Generated by Django 5.1.15 on 2026-09-11 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rcp_numbering_sequence'),
        ('student', '0003_alter_student_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.programme'),
        ),
    ]
