# Generated by Django 5.1.15 on 2026-09-11 15:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20)),
                ('permanent_address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('annual_income', models.CharField(blank=True, max_length=100)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('second_guardian', models.TextField(blank=True)),
                ('school_name', models.CharField(blank=True, max_length=150)),
                ('board', models.CharField(blank=True, max_length=100)),
                ('class_or_course', models.CharField(blank=True, max_length=100)),
                ('medium_of_instruction', models.CharField(blank=True, max_length=100)),
                ('academic_session', models.CharField(blank=True, max_length=20)),
                ('playing_experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('previous_academy', models.CharField(blank=True, max_length=150)),
                ('achievements', models.TextField(blank=True)),
                ('food_preference', models.CharField(blank=True, max_length=100)),
                ('room_preference', models.CharField(blank=True, max_length=100)),
                ('local_guardian_address', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('existing_conditions', models.TextField(blank=True)),
                ('past_injuries', models.TextField(blank=True)),
                ('family_doctor_contact', models.CharField(blank=True, max_length=16)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
