# Generated by Django 5.1.15 on 2026-09-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('trial', 'Trial'), ('selected', 'Selected'), ('admission_pending', 'Admission pending'), ('active', 'Active'), ('medical_hold', 'Medical hold'), ('fee_hold', 'Fee hold'), ('leave', 'Leave'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], db_index=True, default='active', max_length=20),
        ),
    ]
