# Generated by Django 5.1.15 on 2026-08-26 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admission", "0001_initial"),
        ("core", "0004_agecategory_assessmentcriterion_documenttype_and_more"),
        ("enquiry", "0001_initial"),
        ("people", "0002_guardian_staff_studentguardian"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="enquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admissions",
                to="enquiry.enquiry",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admissions",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="programme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admissions",
                to="core.programme",
            ),
        ),
    ]
