# Generated by Django 5.1.15 on 2026-08-26 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admission", "0002_initial"),
        ("core", "0004_agecategory_assessmentcriterion_documenttype_and_more"),
        ("document", "0001_initial"),
        ("trial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="trial_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admissions",
                to="trial.trialregistration",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="trial_waiver_approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.approvalrequest",
            ),
        ),
        migrations.AddField(
            model_name="admissionchecklistitem",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist_items",
                to="admission.admission",
            ),
        ),
        migrations.AddField(
            model_name="admissionchecklistitem",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checklist_items",
                to="document.document",
            ),
        ),
        migrations.AddField(
            model_name="admissionchecklistitem",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.documenttype"
            ),
        ),
        migrations.AddConstraint(
            model_name="admissionchecklistitem",
            constraint=models.UniqueConstraint(
                fields=("admission", "document_type"), name="unique_admission_document_type"
            ),
        ),
    ]
