# Generated by Django 5.1.15 on 2026-09-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="fee_payment_method",
            field=models.CharField(
                blank=True,
                choices=[("upi", "UPI"), ("card", "Card"), ("cash", "Cash")],
                max_length=10,
            ),
        ),
    ]
