# Generated by Django 5.1.15 on 2026-09-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0004_admission_fee_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="fee_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
