# Generated by Django 5.1.15 on 2026-09-11 13:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_remove_waiver_fields_and_add_constraint'),
        ('core', '0006_rcp_numbering_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted', models.BooleanField()),
                ('version', models.CharField(max_length=20)),
                ('granted_at', models.DateTimeField()),
                ('granted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('declared_by_name', models.CharField(max_length=120)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='admission.admission')),
                ('consent_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.consenttype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('admission', 'consent_type'), name='unique_admission_consent_type')],
            },
        ),
    ]
