# Generated by Django 5.1.15 on 2026-09-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_consentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='step',
            field=models.CharField(choices=[('draft', 'Draft'), ('documents_pending', 'Documents pending'), ('documents_verified', 'Documents verified'), ('fee_pending', 'Fee pending'), ('fee_cleared', 'Fee cleared'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('payment_recorded', 'Payment recorded'), ('payment_verified', 'Payment verified'), ('documents_rejected', 'Documents rejected'), ('ready_for_approval', 'Ready for approval'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
