# Generated by Django 5.1.15 on 2026-09-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_alter_admission_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionintake',
            name='guardian_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionintake',
            name='guardian_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
