# Generated by Django 5.1.15 on 2026-08-26 06:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("portal_access", models.BooleanField(default=False)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="people.person"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_code", models.CharField(max_length=20, unique=True)),
                (
                    "staff_type",
                    models.CharField(
                        choices=[
                            ("coach", "Coach"),
                            ("medical", "Medical"),
                            ("physio", "Physio"),
                            ("hostel", "Hostel"),
                            ("transport", "Transport"),
                            ("admin", "Admin"),
                            ("athlete_mgmt", "Athlete Management"),
                        ],
                        max_length=20,
                    ),
                ),
                ("joining_date", models.DateField()),
                ("exit_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="people.person"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_emergency_contact", models.BooleanField(default=False)),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="people.guardian",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardians",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "guardian"), name="unique_student_guardian"
                    )
                ],
            },
        ),
    ]
